name       : trackma
version    : 0.7.1
release    : 4
source     :
    - https://github.com/z411/trackma/archive/v0.7.1.tar.gz : d759a85ce51bc99d13e191b8a0b322d3116f1eedf7b928a4d4339fd522b7330a
license    : GPL-3.0
component  : multimedia.video
summary    : Lightweight and simple client for managing MyAnimeList, Hummingbird, VNDB, and Melative lists
description: |
    Trackma aims to be a lightweight and simple, but feature-rich program for Unix based systems
    for managing personal lists hosted in several media tracking websites.
    Currently supported sites include, MyAnimeList, Hummingbird, VNDB, and Melative.
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - lsof
    - python3-cairo
    - python3-gobject
    - python3-urwid
    - python-pillow
setup      : |
    %python3_setup
install    : |
    %python3_install
    install -D -m 00644 $pkgfiles/trackma.desktop $installdir/usr/share/applications/trackma.desktop
