name       : trackma
version    : 0.7.6
release    : 10
source     :
    - https://github.com/z411/trackma/archive/v0.7.6.tar.gz : 8086f8acf2639cd4aaba527b6b2423d8a948e58d14f5137443288510403348c5
license    : GPL-3.0
component  : multimedia.video
summary    : Lightweight and simple client for managing MyAnimeList, Hummingbird, VNDB, and Melative lists
description: |
    Trackma aims to be a lightweight and simple, but feature-rich program for Unix based systems
    for managing personal lists hosted in several media tracking websites.
    Currently supported sites include, MyAnimeList, Hummingbird, VNDB, and Melative.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - lsof
    - python3-cairo
    - python3-gobject
    - python3-urwid
    - python-pillow
setup      : |
    %python3_setup
install    : |
    %python3_install
    install -D -m 00644 $pkgfiles/trackma.desktop $installdir/usr/share/applications/trackma.desktop
