name       : trackma
version    : 0.8.2
release    : 11
source     :
    - https://github.com/z411/trackma/archive/v0.8.2.tar.gz : 89e693a39cbbb7d31bf169bd272353c7c3dab2cfc4e5609347d66f88f3ba35ee
license    : GPL-3.0
component  : multimedia.video
summary    : Lightweight and simple client for managing MyAnimeList, Hummingbird, VNDB, and Melative lists
description: |
    Trackma aims to be a lightweight and simple, but feature-rich program for Unix based systems
    for managing personal lists hosted in several media tracking websites.
    Currently supported sites include, MyAnimeList, Hummingbird, VNDB, and Melative.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - lsof
    - python3-cairo
    - python3-gobject
    - python3-urwid
    - python-pillow
setup      : |
    %python3_setup
install    : |
    %python3_install
    install -D -m 00644 $pkgfiles/trackma.desktop $installdir/usr/share/applications/trackma.desktop
