name       : trackma
version    : 0.7.5
release    : 9
source     :
    - https://github.com/z411/trackma/archive/v0.7.5.tar.gz : 24f78aacda26849b236017a75a6c73501b98c576f26c976d92ae9386242cc5b4
license    : GPL-3.0
component  : multimedia.video
summary    : Lightweight and simple client for managing MyAnimeList, Hummingbird, VNDB, and Melative lists
description: |
    Trackma aims to be a lightweight and simple, but feature-rich program for Unix based systems
    for managing personal lists hosted in several media tracking websites.
    Currently supported sites include, MyAnimeList, Hummingbird, VNDB, and Melative.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - lsof
    - python3-cairo
    - python3-gobject
    - python3-urwid
    - python-pillow
setup      : |
    %python3_setup
install    : |
    %python3_install
    install -D -m 00644 $pkgfiles/trackma.desktop $installdir/usr/share/applications/trackma.desktop
